export const brandData = [
    { name: "КИТАЙСКИЕ", brand: "VENDOR10" },
    { name: "ОТЕЧЕСТВЕННЫЕ", brand: "VENDOR1" },
    { name: "ИНОМАРКИ", brand: "VENDOR2" },
    { name: "ЕВРОПЕЙСКИЕ", brand: "VENDOR3" },
    { name: "НЕМЕЦКИЕ", brand: "VENDOR4" },
    { name: "ФРАНЦУЗСКИЕ", brand: "VENDOR5" },
    { name: "ЯПОНСКИЕ", brand: "VENDOR7" },
    { name: "КОРЕЙСКИЕ", brand: "VENDOR9" },
    { name: "АМЕРИКАНСКИЕ", brand: "VENDOR8" },
    { name: "ИТАЛЬЯНСКИЕ", brand: "VENDOR6", special: true },
    { name: "Audi", brand: "audi" },
    { name: "BMW", brand: "bmw" },
    { name: "Chevrolet", brand: "chevrolet" },
    { name: "Ford", brand: "ford" },
    { name: "Hyundai", brand: "hyundai" },
    { name: "Kia", brand: "kia" },
    { name: "Mercedes", brand: "mercedes" },
    { name: "Nissan", brand: "nissan" }, 
    { name: "Renault", brand: "renault" },
    { name: "Toyota", brand: "toyota" },
    { name: "Volkswagen", brand: "volkswagen" },
    { name: "ВАЗ", brand: "vaz" },
    { name: "УАЗ", brand: "uaz" },
];